services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=${NEO4J_URI:-neo4j://neo4j:7687}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-your_password}
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - app-network

  neo4j:
    image: neo4j:5.17.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-your_password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_connector_bolt_enabled=true
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687
      - NEO4J_dbms_default__database=neo4j
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "your_password", "RETURN 1;"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app-network:
    driver: bridge
